language: java

jdk:
 - oraclejdk8

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: heroku
  api_key: "85ea1535-d567-4d0a-b04b-3a3115bd0daa"
  app: helloworld-sanzy
  on:
    repo: sighaloic/INGE-4-ISJ-2021-Groupe-5-Integration-Continue	
    branch: sanzy
  skip_cleanup: true

dist: trusty
