language: java

jdk:
 - oraclejdk8

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: heroku
  api_key:
    secure: "2f655d2f-84fb-4cd3-b723-36ab03e6962a"
  app: app-ic
  on:
    repo: INGE-4-ISJ-2021-Groupe-5-Integration-Continue
    branch: payep_branch

dist: trusty
