language: java

jdk:
 - oraclejdk8

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: heroku
  api_key: "4d37acbc-6e96-4f0e-935f-4b50799f6739"
  app: helloworld-v
  on:
    repo: sighaloic/INGE-4-ISJ-2021-Groupe-5-Integration-Continue	
    all_branches: true
  skip_cleanup: true

dist: trusty
