language: java

jdk:
 - oraclejdk8

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: heroku
  api_key: "6d5e7847-256e-4251-aa04-68851678823d"
  app: helloworld-v
  on:
    repo: sighaloic/INGE-4-ISJ-2021-Groupe-5-Integration-Continue	
    all_branches: true
  skip_cleanup: true

dist: trusty
